### ISSUE TITLE
Add an option to start the vignette on a set health level

### ISSUE THREAD

**Issue by RaptaG** [Octol1ttle/DamageVignette-Fabric#11]
For example 10HP, 12 HP etc.

**Comment by Octol1ttle** [comment]
This is already possible using the configuration file, adjust the High Health Threshold. When the current health percentage becomes lower than the High Health Threshold, vignette will appear and its intensity will increase as your health gets lower until reaching Low Health Threshold, at which the vignette will be at its maximum intensity.

**Comment by RaptaG** [comment]
This is why I suggested https://github.com/Octol1ttle/DamageVignette/issues/12
