### ISSUE TITLE
[suggestion] add a heartbeat sound if damage is very low

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Octol1ttle/DamageVignette-Fabric#13]
I noticed lunar had this and I thought it'd be something cool to possibly add. 

Maybe like heartbeat starts at 3 hearts and it gets more intense as it goes down

**Comment by Octol1ttle** [comment]
by "heartbeat" do you mean a sound or a visual pulsing effect?

**Comment by Aces-and-Jacks** [comment]
Sound

**Comment by Aces-and-Jacks** [comment]
And probably pulsing would be cool but mainly sound

**Comment by Octol1ttle** [comment]
The mod is now in maintenance mode. No new features will be worked on.

**Comment by Aces-and-Jacks** [comment]
Ok. Well thank you for still maintaining it instead of dropping support entirely. At least for now

**Comment by Aces-and-Jacks** [comment]
If someone makes a pull request tho would that still be added in if it works?

**Comment by Apceniy** [comment]
I would guess so, considering that @Octol1ttle quit because of being frustrated trying to make things work
