### ISSUE TITLE
Hunger/Air Vignette Colors

### ISSUE THREAD

**Issue by yetanotherparrot** [Octol1ttle/DamageVignette-Fabric#15]
Hello, this damage vignette mod is great since I like to play the game with as little HUD displayed as possible (I also use the AutoHUD mod for this purpose). I was wondering if you could add support for different colors to indicate other player stats such as hunger/air?

It would be great to create the most immersive Minecraft experience yet, since no other mod has as much potential as this one in terms of replacing the HUD.

Thanks! :)

**Comment by Octol1ttle** [comment]
The mod is now in maintenance mode. No new features will be worked on.
