### ISSUE TITLE
Vignette with Iris Shaders not working

### ISSUE THREAD

**Issue by Hadeslnc** [Octol1ttle/DamageVignette-Fabric#2]
Hence in 1.0.1 fixed incompatibility with shaders mod Iris, its still not working. Enabling any shader completely disables mod vignette.

**[Without Shaders]**
![2023-01-27_12 46 28](https://user-images.githubusercontent.com/43775511/215056507-9f05571f-08fc-46cc-a010-f3b263412449.png)

**[Shaders Enabled]**
![2023-01-27_12 42 50](https://user-images.githubusercontent.com/43775511/215056259-ed561013-7e71-4b6d-a867-95c9230b0909.png)

**Comment by Octol1ttle** [comment]
Please report to Iris, they have a Mixin that disables vignette when shaders are enabled.

**Comment by nco2k** [comment]
your mod doesnt work for me, even when i disable shaders. but this [datapack](https://www.planetminecraft.com/data-pack/visual-health-warning/) works, even with shaders.

**Comment by Octol1ttle** [comment]
Try again with https://modrinth.com/mod/damagevignette/version/3.0.0

**Comment by nco2k** [comment]
thanks, its working now (even with shaders). any chance you could give us an option to choose at how many hearts the effect will start showing, and the intensity of the effect?

**Comment by Apceniy** [comment]
The mod has a config where you can set this up for you

**Comment by nco2k** [comment]
> The mod has a config where you can set this up for you

not anymore. config has been removed in 3.0.0. i just double checked to see if there is a damagevignette.json somewhere like in 2.0.2, but its gone.
